import React from "react";
import Head from "next/head";

import { CustomerInformationLayout } from "@/components/layout";
import { NewCustomer } from "@/components/customers";
import { getUserById } from "@/store/customers/api";

const EditCustomerPage = (data: any) => {
  return (
    <>
      <Head>
        <title>Customers Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <NewCustomer type="edit" data={data} />
      </main>
    </>
  );
};

export const getServerSideProps = async (context: any) => {
  const res = await getUserById(context.query?.id);
  const data = res?.data;
  return {
    props: data,
  };
};
EditCustomerPage.Layout = CustomerInformationLayout;
export default EditCustomerPage;
