import React from "react";
import Head from "next/head";

import { CustomerLayout } from "@/components/layout";
import { NewCustomer } from "@/components/customers";

const NewCustomerPage = () => {
  return (
    <>
      <Head>
        <title>New Customer Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <NewCustomer data="" />
      </main>
    </>
  );
};

NewCustomerPage.Layout = CustomerLayout;
export default NewCustomerPage;
