import React from "react";

import { CustomerLayout } from "@/components/layout";
import { ListView } from "@/components/customers";
import Head from "next/head";

const ListCustomer = () => {
  return (
    <>
      <Head>
        <title>Customers Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <ListView />
      </main>
    </>
  );
};

ListCustomer.Layout = CustomerLayout;
export default ListCustomer;
